### ISSUE TITLE
[US] Check-out

### ISSUE THREAD

**Issue by iGormilhit** [inveniosoftware/invenio-circulation#1]
As a librarian, I check-out an item for a patron, so that he can take it home.

### Tasks:
- [x] Fix the tests
- [x] #25 Create REST endpoint for checkout
- [x] #26 Checkout: implement access restriction to the REST endpoints
- [x] #48 Checkout: Check item availability on checkout
